name: Invocar acción de validación

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  invoke-validation-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Invoke validation action
        uses: omartinex/jmf-infra/.github/workflows/validate_config.yml@v0.1
